services:
  - type: web
    name: boty-1
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 5000
      - key: cook
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: ALIEXPRESS_APP_KEY
        sync: false
      - key: ALIEXPRESS_APP_SECRET
        sync: false
